const bills_cards = [
  {
    id: 1,
    name: "Axis My Choice Credit Card",
    benefits: [
      "Enjoy 5% cashback on any of the two spending categories-Supermarkets, Fuel, Travel, Utility Bills, Electronics and Dining",
      "Transaction of more than ₹2,500 can be converted into EMIs",
    ],
    minAge: 18,
    maxAge: 70,
    income: 15000,
    cScore: 750,
    joiningFee: 250,
    renewalFee: 250,
    link: "https://www.wishfin.com/axis-my-choice-credit-card/",
    img: "https://s3-ap-southeast-1.amazonaws.com/paymatrixuploads/static/new_home/credit_card_images/axis_bank_my_zone_credit_card.png",
  },
  {
    id: 2,
    name: "Axis Bank Ace Credit Card",
    benefits: [
      "Get a Cashback of 5% on bill payment of the electricity bills, gas bills, DTH bills, and other utility bills on Google Pay through this credit card",
      "There is no upper limit on Cashback.",
    ],
    minAge: 18,
    maxAge: 70,
    income: 15000,
    cScore: 750,
    joiningFee: 499,
    renewalFee: 499,
    link: "https://www.wishfin.com/axis-bank-ace-credit-card/",
    img: "https://www.cardexpert.in/wp-content/uploads/2020/10/axis-bank-ace-credit-card-1.jpg",
  },
  {
    id: 3,
    name: "Citibank Citi Cash Back Credit Card",
    benefits: [
      "5% cashback on all utility bill payments paid through Citibank online bill pay",
      "5% cashback on all telephone bill payments",
    ],
    minAge: 18,
    maxAge: 70,
    income: 15000,
    cScore: 750,
    joiningFee: 500,
    renewalFee: 500,
    link: "https://www.wishfin.com/citibank-citi-cash-back-credit-card/",
    img: "https://cardinsider.com/wp-content/uploads/2021/07/Citi-Cash-Back-Credit-Card.png",
  },
  {
    id: 4,
    name: "SBI Card PRIME",
    benefits: [
      "Get a welcome e-gift worth ₹3,000 from any of these brands – Marks and Spencer, Yatra.com, Shopper Stop, Bata/Hush Puppies and Pantaloons",
      "Earn 20 reward points on every ₹100 spent on standing instructions of utility bill payments",
    ],
    minAge: 21,
    maxAge: 70,
    income: 15000,
    cScore: 700,
    joiningFee: 2999,
    renewalFee: 2999,
    link: "https://www.wishfin.com/sbi-card-prime/",
    img: "https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/rewards/card-faces/sbi-prime-cardface.png",
  },
  {
    id: 5,
    name: "Super Value Titanium Credit Card Benefits",
    benefits: ["Telephone bills – 5% cashback", "Utility bills – 5% cashback"],
    minAge: 21,
    maxAge: 65,
    income: 55000,
    cScore: 700,
    joiningFee: 500,
    renewalFee: 2500,
    link: "https://www.sc.com/in/credit-cards/super-value-titanium/",
    img: "https://aayushbhaskar.com/wp-content/uploads/2020/08/standard-chartered-1.png",
  },
];

module.exports = bills_cards;
