const food_travel = [
  {
    id: 1,
    name: "American Express Platinum Travel credit card",
    priority: 3,
    benefits: [
      "15 to 20% instant discount on partner restaurants.",
      "Get a Taj Stay vouchers worth Rs. 10,000 from Taj, SeleQtions and Vivanta Hotels.",
      "Earn Rewards points redeemable for Amex Travel Online upto worth Rs. 7,500.",
      "Enjoy 8 complimentary visits per year to airport lounges across India.",
    ],
    minAge: 21,
    maxAge: 60,
    income: 50000,
    cScore: 750,
    joiningFee: 3500,
    renewalFee: 5000,
    link: "https://www.americanexpress.com/in/credit-cards/platinum-travel-credit-card/",
    img: "https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/c3bbd7ad-6a6e-4c7b-92f9-319d5859567c/Personal/Pay/Cards/Credit%20Card/Credit%20Card%20Landing%20Page/Credit%20Cards/Super%20Premium/Regalia/Regalia-MC.png",
  },
  {
    id: 2,
    name: "Standard Chartered Ultimate Credit Card",
    priority: 4,
    benefits: [
      "Up to 25% discount for dining at top 250 restaurants across India.",
      "5% cashback* on duty free spends and access to over 1000 airport lounges.",
      "Enjoy reduced foreign currency markup fee of 2% on all foreign currency transactions.",
    ],
    minAge: 21,
    maxAge: 65,
    income: 0,
    cScore: 750,
    joiningFee: 5000,
    renewalFee: 5000,
    link: "https://www.sc.com/in/credit-cards/ultimate-card/",
    img: "https://www.credithita.com/images/cards/standard-chartered-ultimate-credit-card.jpg",
  },
  {
    id: 3,
    name: "Citi PremierMiles Credit Card",
    priority: 5,
    benefits: [
      "Earn 10 miles for every Rs. 100 spent on airline transactions.",
      "Redeem miles across 100+ airlines and hotel partners.",
      "Up to 20% savings across participating restaurants.",
    ],
    minAge: 21,
    maxAge: 60,
    income: 0,
    cScore: 750,
    joiningFee: 3000,
    renewalFee: 3000,
    link: "https://www.online.citibank.co.in/credit-card/travel/citi-premiermiles-card",
    img: "https://www.paisabazaar.com/wp-content/uploads/2019/07/citi-premiermiles-card.jpg",
  },
];

module.exports = food_travel;
