const movieShopping = [
  {
    id: 1,
    name: "Axis Bank Neo Credit Card",
    priority: 2,
    benefits: [
      "10% off on movies, groceries and online shopping",
      "Get 10% off every time on shopping with Myntra",
    ],
    MinAge: 18,
    MaxAge: 70,
    joiningFee: 250,
    renewalFee: 250,
    income: 25000,
    cScore: 750,
    link: "https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card/features-benefits",
    img: "https://s3-ap-southeast-1.amazonaws.com/paymatrixuploads/static/new_home/credit_card_images/axis_bank_neo_credit_card.png",
  },
  {
    id: 2,
    name: "SBI Card Prime",
    priority: 2,
    benefits: [
      "Welcome e-gift Voucher worth Rs. 3,000 from any of the following brands: Bata/Hush Puppies, Pantaloons, Aditya Birla Fashion, Shoppers Stop and Yatra.com.",
      "10 reward points per Rs. 100 spent on dining, groceries, departmental stores, and movies",
    ],
    MinAge: 21,
    MaxAge: 70,
    joiningFee: 3000,
    renewalFee: 3000,
    income: 75000,
    cScore: 750,
    link: "https://www.sbicard.com/en/personal/credit-cards/rewards/sbi-card-prime.page",
    img: "https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/rewards/card-faces/sbi-prime-cardface.png",
  },
  {
    id: 3,
    name: "Axis Bank My Zone Credit Card",
    priority: 2,
    benefits: [
      "Buy one get one free on movie tickets.",
      "Up to 25% off at Myntra.",
    ],
    MinAge: 18,
    MaxAge: 70,
    joiningFee: 500,
    renewalFee: 500,
    income: 25000,
    cScore: 700,
    link: "https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card/features-benefits",
    img: "https://images.fintra.co.in/cms/axis-bank-my-zone-easy-credit-card.png",
  },
  {
    id: 4,
    name: "SBI Card Elite",
    priority: 2,
    benefits: [
      "Welcome e-gift voucher worth rs 5000: Yatra, Hush Puppies/Bata, Pantaloons, Aditya Birla Fashion and Shoppers Stop",
      "Get 5X Reward Points on Dining, Departmental stores and Grocery Spends.",
      "Free Movie Tickets worth Rs. 6,000 every year.",
    ],
    MinAge: 18,
    MaxAge: 70,
    joiningFee: 500,
    renewalFee: 500,
    income: 25000,
    cScore: 700,
    link: "https://www.sbicard.com/en/personal/credit-cards/lifestyle/sbi-card-elite.page",
    img: "https://www.paisabazaar.com/wp-content/uploads/2017/10/Elite-CS6-01.png",
  },
];

module.exports = movieShopping;
