const movieFood = [
  {
    id: 1,
    name: "Axis Bank My Zone Credit Card",
    priority: 3,
    benefits: [
      "Buy one get one free on movie tickets.",
      "Get 40% off on food delivery at Swiggy.",
    ],
    MinAge: 18,
    MaxAge: 70,
    joiningFee: 500,
    renewalFee: 500,
    income: 25000,
    cScore: 700,
    link: "https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card/features-benefits",
    img: "https://images.fintra.co.in/cms/axis-bank-my-zone-easy-credit-card.png",
  },
  {
    id: 2,
    name: "Axis Bank Neo Credit Card",
    priority: 3,
    benefits: [
      "40% off on Zomato",
      "Minimum 15% off on dining at partner restaurants",
      "10% off on movies, groceries and online shopping",
    ],
    MinAge: 18,
    MaxAge: 70,
    joiningFee: 250,
    renewalFee: 250,
    income: 25000,
    cScore: 750,
    link: "https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card/features-benefits",
    img: "https://s3-ap-southeast-1.amazonaws.com/paymatrixuploads/static/new_home/credit_card_images/axis_bank_neo_credit_card.png",
  },
  {
    id: 3,
    name: "Citi Cashback Credit Card",
    priority: 3,
    benefits: [
      "Up to 20% savings across participating restaurants.",
      "5% Cashback on Movies, bills and telephone",
    ],
    MinAge: 18,
    MaxAge: 70,
    joiningFee: 250,
    renewalFee: 250,
    income: 25000,
    cScore: 750,
    link: "https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card/features-benefits",
    img: "https://s3-ap-southeast-1.amazonaws.com/paymatrixuploads/static/new_home/credit_card_images/axis_bank_neo_credit_card.png",
  },
  {
    id: 4,
    name: "Kotak Delight Platinum Credit Card",
    priority: 3,
    benefits: ["10% Cashback on Movies", "10% Cashback on Dining"],
    MinAge: 21,
    MaxAge: 65,
    joiningFee: 2000,
    renewalFee: 300,
    income: 0,
    cScore: 750,
    link: "https://www.kotak.com/en/personal-banking/cards/credit-cards/delight-platinum-card/features.html",
    img: "https://1.bp.blogspot.com/-BEhLJl2k7S8/XxLCQuG-u7I/AAAAAAAAEZA/GPlHXQc6GZYh14mbDcepY2o0ZJQxEYTFwCLcBGAsYHQ/s490/Delight%2BPlatinum%2BCredit%2BCard.jpg",
  },
];

module.exports = movieFood;
