const Movies = [
  {
    id: 1,
    name: "SBI Elite Credit Card",
    priority: 1,
    benefits: [
      "Free Movie Tickets worth Rs. 6,000 every year.",
      "Transaction valid for at least 2 tickets per booking per month.",
      "5X Reward Points on Dining, Departmental stores and Grocery Spends.",
    ],
    MinAge: 18,
    MaxAge: 70,
    income: 60000,
    cScore: 750,
    joiningFee: 4999,
    renewalFee: 4999,
    link: "https://www.sbicard.com/en/personal/credit-cards/lifestyle/sbi-card-elite.page",
    img: "https://www.paisabazaar.com/wp-content/uploads/2017/10/Elite-CS6-01.png",
  },
  {
    id: 2,
    name: "ICICI Instant Platinum Credit Card",
    priority: 1,
    benefits: [
      "Get a discount of Rs. 100 on movie ticket booking. It can be availed twice a month.",
    ],
    MinAge: 18,
    MaxAge: 60,
    income:
      "The applicant must have a fixed deposit with ICICI Bank of at least Rs. 20,000 and with a tenure of at least 180 days or more.",
    cScore: 750,
    joiningFee: "NIL",
    renewalFee: "NIL",
    link: "https://campaigns.icicibank.com/credit-card/platinumCreditCard/index.html?utm_source=sem&utm_medium=search&utm_campaign=icicibank-a4-search-credit-card-core-cc-platinum-brand-card-type-exact-apr&utm_content=sem-search-icicibank-a4-search-credit-card-core-cc-platinum-brand-card-type-exact-apr-performance-na-cpc-Platinum-Instant-na-icici-instant-platinum-credit-card&utm_term=icici-instant-platinum-credit-card&utm_lms=sem-search-icicibank-a4-search-credit-card-core-cc-platinum-brand-card-type-exact-apr-performance-na-cpc-Platinum-Instant-na-icici-instant-platinum-credit-card&gclid=CjwKCAjwtcCVBhA0EiwAT1fY7xK806GVqCHNTTQvTGGxzltybG1dADtno-4qBtnLPCyD-TjRnOWIUhoCCRkQAvD_BwE",
    img: "https://cdn2.desidime.com/topics/photos/1248688/original/icici_platinum_master_card_new.png?1611376748",
  },
  {
    id: 3,
    name: "Citibank Cashback Credit Card",
    priority: 1,
    benefits: [
      "Book 2 movie tickets to get 100% off up to Rs.300 on your second ticket every Friday.",
      "Transaction valid for at least 2 tickets per booking per month.",
      "5X Reward Points on Dining, Departmental stores and Grocery Spends.",
    ],
    MinAge: 21,
    MaxAge: 60,
    income: 20000,
    cScore: 750,
    joiningFee: 500,
    renewalFee: 500,
    link: "https://www.online.citibank.co.in/credit-card/cash-back/citi-cash-back-credit-card",
    img: "https://static.paisabazaar.com/components/images/credit_card/small_images/50.png",
  },
  {
    id: 4,
    name: "RBL Platinum Maxima Credit Card",
    priority: 1,
    benefits: [
      "Get one complimentary movie ticket free up to Rs. 200 every month on purchase of 2 or more tickets at BookMyShow.",
      "Get 2 complimentary visits every calendar quarter at domestic lounges at all  major airports in India.",
    ],
    MinAge: 23,
    MaxAge: 60,
    income: 25000,
    cScore: 750,
    joiningFee: 2000,
    renewalFee: 2000,
    link: "https://www.rblbank.com/product/credit-cards/platinum-maxima-card",
    img: "https://static.smartspends.com/static/images/creditcard/RBL109.png",
  },
  {
    id: 5,
    name: "HDFC Platinum Times Card",
    priority: 1,
    benefits: ["25% off on Movie Tickets on BookMyShow.", ""],
    MinAge: 21,
    MaxAge: 60,
    income: 35000,
    cScore: 700,
    joiningFee: 1000,
    renewalFee: 1000,
    link: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/platinum-times-credit-card",
    img: "https://cardinsider.com/wp-content/uploads/2021/06/HDFC-Platinum-Times-Card.png",
  },
];

module.exports = Movies;
