const shoppingFood = [
  {
    id: 1,
    name: "RBL Bank Edition Clasic Credit Card",
    priority: 7,
    benefits: [
      "5 Edition Cash on every Rs. 100 spent on dining or food purchases made on Zomato",
      "1 Edition Cash on every Rs. 100 spent everywhere else",
      "Enjoy the exclusive privileges of Zomato Pro with a complimentary annual membership, valid across India. Your membership gets automatically renewed every year.",
    ],
    minAge: 21,
    maxAge: 70,
    income: 15000,
    cScore: 700,
    joiningFee: 500,
    renewalFee: 500,
    link: "https://www.rblbank.com/product/credit-cards/edition-classic-credit-card",
    img: "https://www.cardexpert.in/wp-content/uploads/2020/03/rbl-bank-edition-classic-credit-card.png",
  },
  {
    id: 2,
    name: "Axis Bank My Zone Credit Card",
    priority: 7,
    benefits: [
      "Get a 40% discount on all online food orders with code AXIS40",
      "Fuel surcharge waivers at petrol pumps across India",
    ],
    minAge: 21,
    maxAge: 70,
    income: 15000,
    cScore: 700,
    joiningFee: 500,
    renewalFee: 500,
    link: "https://www.mycreditcardclub.com/5-best-credit-cards-for-swiggy-and-zomato/",
    img: "http://cardmaven.in/wp-content/uploads/2021/12/Axis-Bank-MY-Zone-Credit-Card.png",
  },
  {
    id: 3,
    name: "HSBC Cashback Credit Card",
    priority: 7,
    benefits: [
      "Enjoy 2 Meal Vouchers of ₹400 each and use them at the Airport Restaurants.",
      "Earn a Cashback of 1.5% on all the Online transactions.",
    ],
    minAge: 21,
    maxAge: 70,
    income: 15000,
    cScore: 700,
    joiningFee: 500,
    renewalFee: 500,
    link: "https://www.wishfin.com/hsbc-cashback-credit-card/",
    img: "https://www.hsbc.co.in/content/dam/hsbc/in/images/credit-card/cashback-credit-card.jpg",
  },
];

module.exports = shoppingFood;
