const shoppingTravel = [
  {
    id: 1,
    name: "Paytm SBI Credit Card",
    priority: 8,
    benefits: [
      "Up to 5% cashback on all travel, movies, and many more services, on every transaction",
      "1% fuel surcharge waiver on every transaction ranging from Rs. 500 to Rs. 3,000",
      "2% cashback on All other purchases on Paytm app",
    ],
    minAge: 21,
    maxAge: 70,
    income: 15000,
    cScore: 700,
    joiningFee: 500,
    renewalFee: 499,
    link: "https://www.paisabazaar.com/sbi-bank/paytm-sbi-credit-card/",
    img: "https://qph.cf2.quoracdn.net/main-qimg-bddaaaf809456649eedb3e6030b466c7-lq",
  },
  {
    id: 2,
    name: "HDFC Diners Club Black Credit Card",
    priority: 8,
    benefits: [
      "Unlimited Airport lounge access to 700 and more lounges both nationally and internationally",
      "3.3% reward rate is on 10X profits on Smartbuy and partner brands (Tata, Swiggy, BigBasket, Uber, BookMyShow&Treebo Hotels)",
    ],
    minAge: 21,
    maxAge: 60,
    income: 15000,
    cScore: 700,
    joiningFee: 1000,
    renewalFee: 5000,
    link: "https://moneymint.com/hdfc-diners-club-black-credit-card-review/",
    img: "https://cdn.moneymint.com/wp-content/uploads/2019/10/How-to-Apply-for-HDFC-Diners-Club-Black-Credit-Card-online.png.webp",
  },
  {
    id: 3,
    name: "ICICI Sapphiro Credit Card",
    priority: 8,
    benefits: [
      "Get four complimentary access to select airport lounges in India each quarter",
      "EaseMyTrip Vouchers worth ₹ 4000 (Four vouchers worth ₹ 1000 each)",
    ],
    minAge: 21,
    maxAge: 60,
    income: 15000,
    cScore: 700,
    joiningFee: 6000,
    renewalFee: 3500,
    link: "https://www.icicibank.com/Personal-Banking/cards/Consumer-Cards/Credit-Card/sapphiro-card/key-privileges.page",
    img: "https://cardinsider.com/wp-content/uploads/2021/07/ICICI-Bank-Sapphiro-Credit-Card.png",
  },
];

module.exports = shoppingTravel;
