const Shopping = [
  {
    id: 1,
    name: "Flipkart Axis Bank Credit Card",
    priority: 1,
    benefits: [
      "Welcome benefits worth Rs. 600",
      "5% cashback on shopping with Flipkart and Myntra",
      "4% cashback on shopping with other Preferred Merchant",
      "4% cashback on Swiggy, Cleartrip, Cure.fit, PVR, UBER",
    ],
    minAge: 18,
    maxAge: 70,
    income: 15000,
    cScore: 700,
    joiningFee: 500,
    renewalFee: 499,
    link: "https://www.paisabazaar.com/axis-bank/flipkart-axis-bank-credit-card/",
    img: "https://www.paisabazaar.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2021/01/Flipkart-cart-1-300x191.jpg.webp",
  },
  {
    id: 2,
    name: "Amazon Pay ICICI Credit Card",
    priority: 1,
    benefits: [
      "5% cashback on all purchases made on Amazon",
      "2% cashback on transactions made for flight bookings",
    ],
    minAge: 18,
    maxAge: 60,
    income: 35000,
    cScore: 700,
    joiningFee: null,
    renewalFee: null,
    link: "https://www.paisabazaar.com/icici-bank/icici-bank-amazon-pay-credit-card/",
    img: "https://www.paisabazaar.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2019/05/Amazon-Pay-ICICI-Credit-Card.png.webp",
  },
  {
    id: 3,
    name: "HDFC Millennia Credit Card",
    priority: 1,
    benefits: [
      "5% cashback on Shopping via Amazon, BookMyShow, Cult.fit, Flipkart, Myntra, Sony LIV, Swiggy, Tata CLiQ, Uber and Zomato",
      "1% cashback on all other spends (except fuel)",
    ],
    minAge: 21,
    maxAge: 40,
    income: 35000,
    cScore: 750,
    joiningFee: 1000,
    renewalFee: 1000,
    link: "https://www.paisabazaar.com/hdfc-bank/millennia-credit-card/",
    img: "https://www.paisabazaar.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2017/10/Millennia-VISA-CC.jpg.webp",
  },
  {
    id: 4,
    name: "SBI SimplyCLICK Credit Card",
    priority: 1,
    benefits: [
      "10 reward points per Rs. 100 spent on online purchases made on Amazon/ Apollo24X7/ BookMyShow/ Cleartrip/ Eazydiner/ Lenskart/ Netmeds",
      "5 reward points per Rs. 100 spent on all other online purchases",
    ],
    minAge: 18,
    maxAge: 60,
    income: 25000,
    cScore: 750,
    joiningFee: 499,
    renewalFee: 499,
    link: "https://www.paisabazaar.com/sbi-bank/simplyclick-credit-card/",
    img: "https://www.paisabazaar.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2019/05/SBI-SimplyClick-Credit-Card.png.webp",
  },
  {
    id: 5,
    name: "HSBC Cashback Credit Card",
    priority: 1,
    benefits: [
      "1.5% cashback on all online spending (excluding transfer to online wallets)",
      "Amazon vouchers (worth Rs. 1,000)",
      "Big Basket voucher (worth Rs. 250)",
      "Myntra vouchers Rs.300 x 5 (worth Rs.1,500)",
      "Ajio vouchers  Rs.600 x 5 (worth Rs.3,000)",
    ],
    minAge: 18,
    maxAge: 60,
    income: 33333,
    cScore: 700,
    joiningFee: 750,
    renewalFee: null,
    link: "https://www.paisabazaar.com/hsbc-bank/cashback-credit-card/",
    img: "https://www.paisabazaar.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/01/cashback-credit-card.jpg.webp",
  },
];

module.exports = Shopping;
