const travel = [
  {
    id: 1,
    name: "Citi PremierMiles Card",
    priority: 1,
    benefits: [
      "10 Miles / Rs.100 on airline transactions",
      "Redeem miles across 100+ airlines and hotel partners.",
      "Complimentary access to select airport lounges across India",
    ],
    minAge: 21,
    maxAge: 60,
    income: 0,
    cScore: 750,
    joiningFee: 3000,
    renewalFee: 3000,
    link: "https://www.online.citibank.co.in/credit-card/travel/citi-premiermiles-card",
    img: "https://www.paisabazaar.com/wp-content/uploads/2019/07/citi-premiermiles-card.jpg",
  },
  {
    id: 2,
    name: "Air India SBI Signature credit card",
    priority: 1,
    benefits: [
      "Get 20,000 Reward points* as a welcome gift on payment of your joining fee",
      "Enjoy the complimentary Visa Lounge Access Program in India at major domestic airports.",
      "Convert your Reward points into Air India miles",
    ],
    minAge: 18,
    maxAge: 65,
    income: 16666,
    cScore: 750,
    joiningFee: 5000,
    renewalFee: 5000,
    link: "https://www.sbicard.com/en/personal/credit-cards/travel/air-india-sbi-signature-card.page",
    img: "https://www.paisabazaar.com/wp-content/uploads/2017/10/SBI_Air_India_Signature_Visa_Card-01-01.png",
  },
  {
    id: 3,
    name: "HDFC Regalia Credit Card",
    priority: 1,
    benefits: [
      "12 Complimentary Airport Lounge Access within India and 6 outside India",
      "Earn 4 Reward Points on every Rs.150 spent .",
    ],
    minAge: 21,
    maxAge: 65,
    income: 100000,
    cScore: 750,
    joiningFee: 2500,
    renewalFee: 2500,
    link: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia",
    img: "https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/c3bbd7ad-6a6e-4c7b-92f9-319d5859567c/Personal/Pay/Cards/Credit%20Card/Credit%20Card%20Landing%20Page/Credit%20Cards/Super%20Premium/Regalia/Regalia-MC.png",
  },
];

module.exports = travel;
